fix: Set default Brew install dir

diff --git a/bin/brew-install b/bin/brew-install
--- a/bin/brew-install
+++ b/bin/brew-install
@@ -6,8 +6,8 @@ ANSIBLE_NEEDED="2.0"
 # Only OS X yosemite and later support xhyve
 OSX_NEEDED="10.10.0"
 
-# This is fork from original
-REPO='itcig/cig-sdk'
+# Root SDK directory installed by homebrew
+CIG_SDK_DIR='/usr/local/cig-sdk'
 
 # Returns 1 if upgrade is needed
 # $1 - SYSTEM VERSION
@@ -69,8 +69,11 @@ else
   echo "ERROR: You need to have 10gb available space."
 fi
 
-# Check out a copy of this repo (first time only) ##
-CIG_SDK_DIR=/usr/local/cig-sdk
+# Check that SDK is installed
+if ! [ -d "$CIG_SDK_DIR" ]; then
+  echo "ERROR: CIG_SDK_DIR not defined"
+  exit 1
+fi
 
 echo 'Handing Playbook to Ansible (will require your sudo password)...'
 echo -e "\n"
